### ISSUE TITLE
Error: While Connects a Node

### ISSUE THREAD

**Issue by apassenger** [SoftwareQuTech/CQC-Python#10]
Hello,
I installed simulaqron and cqc successfully. I have no error or no warning message at his point. However I cannot connect to node and My code return an error after this sentences 
    with CQCConnection("Alice") as Alice:
And my error message is here : 
    File "C:\Users\Visitor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cqc\pythonLib.py", line 298, in __init__
    self._s.connect(addr[4])

So I thougt that maybe socket adress cannot be found and I tried this code:
      with CQCConnection("Alice", socket_address=("1.1.1.1", 8801)) as Alice:
But then I have this error sentences:
   Traceback (most recent call last):
  File "C:/Users/Visitor/.PyCharm2019.1/config/scratches/scratch.py", line 60, in <module>
    main()
  File "C:/Users/Visitor/.PyCharm2019.1/config/scratches/scratch.py", line 7, in main
    with CQCConnection("Alice", socket_address=("1.1.1.1", 8801)) as Alice:
  File "C:\Users\Visitor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cqc\pythonLib.py", line 309, in __init__
    raise err
  File "C:\Users\Visitor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cqc\pythonLib.py", line 298, in __init__
    self._s.connect(addr[4])
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Do you have any idea for this issue? Could you help me please ?

**Comment by AckslD** [comment]
@apassenger I'm closing this issue since we communicated over email. For anyone interested, SimulaQron is currently not supported on windows.
